node ("node02"){

    stage ('Get source code') {
        git branch: "${branch}" url: 'https://github.com/sslbacyhadls/ipr'
    }

    stage ('Preparation') {
      dir('maven_app') {
        env.APP_VER = sh( script: 'mvn help:evaluate -Dexpression=project.version -q -DforceStdout', returnStdout: true).trim()
        sh "echo ${env.APP_VER}"
      }
    }

    stage ('Maven test'){
      dir('maven_app') {
        sh 'mvn test'
      }
    }

    stage ('Build') {
      dir ("maven_app"){
        sh 'mvn clean install'
      }
    }

    stage ('Deply to server') {
      dir ('maven_app')
    }
}
