pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Starting build process'
            }
        }
        stage('Testing') {
            steps {
                echo 'Start testing build'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Something with deploy steps'
            }
        }
    }
}
